# Generated by Django 5.2.4 on 2025-08-15 15:35

import django.db.models.deletion
import siniestros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0005_vehiculo_poliza_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=100, verbose_name='Número de Siniestro y Compañía')),
                ('fecha_siniestro', models.DateField()),
                ('tipo_siniestro', models.CharField(choices=[('RESPONSABILIDAD_CIVIL', 'Responsabilidad Civil Extracontractual'), ('DANOS_PROPIOS', 'Daños Propios')], max_length=30)),
                ('subtipo_rc', models.CharField(blank=True, choices=[('SOLO_DANOS', 'Solo Daños'), ('DANOS_LESIONES_1', 'Daños y Lesiones a 1 Persona'), ('LESIONES_1', 'Lesiones a 1 Persona'), ('LESIONES_2_MAS', 'Lesiones a 2 o más Personas'), ('DANOS_MUERTE_1', 'Daños y Muerte a 1 Persona'), ('DANOS_MUERTE_2_MAS', 'Daños y Muerte a 2 o más Personas'), ('MUERTE_1', 'Muerte a 1 Persona'), ('MUERTE_2_MAS', 'Muerte a 2 o más Personas')], max_length=30, null=True, verbose_name='Subtipo (Resp. Civil)')),
                ('subtipo_dp', models.CharField(blank=True, choices=[('PERDIDA_PARCIAL_DANOS', 'Pérdida Parcial Daños'), ('PERDIDA_PARCIAL_HURTO', 'Pérdida Parcial Hurto'), ('PERDIDA_TOTAL_DANOS', 'Pérdida Total Daños'), ('PERDIDA_TOTAL_HURTO', 'Pérdida Total Hurto')], max_length=30, null=True, verbose_name='Subtipo (Daños Propios)')),
                ('descripcion', models.TextField(verbose_name='Descripción del Siniestro')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('PENDIENTE_DOCUMENTOS', 'Pendiente de Documentos'), ('CERRADO_A_FAVOR', 'Cerrado a Favor del Cliente'), ('CERRADO_EN_CONTRA', 'Cerrado en Contra del Cliente')], default='NUEVO', max_length=30)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-fecha_siniestro'],
            },
        ),
        migrations.CreateModel(
            name='FotoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=siniestros.models.get_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='siniestros.siniestro')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=siniestros.models.get_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='siniestros.siniestro')),
            ],
        ),
    ]
