# Generated by Django 5.2.4 on 2025-09-09 14:53

import django.db.models.deletion
import siniestros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=100, verbose_name='Número de Siniestro y Compañía')),
                ('fecha_siniestro', models.DateField()),
                ('descripcion', models.TextField(verbose_name='Descripción del Siniestro')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('PENDIENTE_DOCUMENTOS', 'Pendiente de Documentos'), ('CERRADO_A_FAVOR', 'Cerrado a Favor del Cliente'), ('CERRADO_EN_CONTRA', 'Cerrado en Contra del Cliente')], default='NUEVO', max_length=30)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza')),
                ('subtipos_afectados', models.ManyToManyField(related_name='siniestros', to='siniestros.subtiposiniestro')),
            ],
            options={
                'ordering': ['-fecha_siniestro'],
            },
        ),
        migrations.CreateModel(
            name='FotoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=siniestros.models.get_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='siniestros.siniestro')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=siniestros.models.get_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='siniestros.siniestro')),
            ],
        ),
        migrations.AddField(
            model_name='subtiposiniestro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='siniestros.tiposiniestro'),
        ),
    ]
