# Generated by Django 5.2.4 on 2025-08-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='subtipo_dp',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='subtipo_rc',
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='tipo_siniestro',
        ),
        migrations.AddField(
            model_name='siniestro',
            name='subtipos_afectados',
            field=models.ManyToManyField(related_name='siniestros', to='siniestros.subtiposiniestro'),
        ),
        migrations.AddField(
            model_name='subtiposiniestro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='siniestros.tiposiniestro'),
        ),
    ]
