# Generated by Django 5.2.4 on 2025-07-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniaAseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Compañía Aseguradora',
                'verbose_name_plural': 'Compañías Aseguradoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('poliza_pdf', models.FileField(blank=True, null=True, upload_to='polizas_pdf/')),
                ('prima_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Prima Total')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 15.00 para 15%', max_digits=5, verbose_name='Porcentaje de Comisión (%)')),
                ('modo_pago', models.CharField(choices=[('CONTADO', 'De Contado'), ('CREDITO', 'A Crédito'), ('MENSUAL', 'Pago Mensual')], default='CONTADO', max_length=10, verbose_name='Modalidad de Pago')),
                ('plazo_meses', models.PositiveIntegerField(default=12, help_text='Relevante para pago a Crédito o Mensual', verbose_name='Plazo en Meses')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=10, verbose_name='Estado de la Póliza')),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to=settings.AUTH_USER_MODEL)),
                ('compania_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='polizas.companiaaseguradora')),
                ('tipo_seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='polizas.tiposeguro')),
            ],
            options={
                'ordering': ['-fecha_fin'],
            },
        ),
    ]
