# Generated by Django 5.2.4 on 2025-09-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniaAseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Compañía Aseguradora',
                'verbose_name_plural': 'Compañías Aseguradoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Porcentaje de Comisión (%)')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19.0, help_text='Ej: 19.00 para 19%', max_digits=5, verbose_name='Porcentaje de IVA (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa única del vehículo.', max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('soat_vencimiento_recordatorio', models.DateField(blank=True, help_text='Fecha de vencimiento del SOAT (incluso si no es de Assecol).', null=True, verbose_name='Recordatorio Vencimiento SOAT')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('poliza_pdf', models.FileField(blank=True, null=True, upload_to='polizas_pdf/')),
                ('valor_prima_sin_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Prima sin IVA')),
                ('modo_pago', models.CharField(choices=[('CONTADO', 'De Contado'), ('CREDITO', 'A Crédito'), ('MENSUAL', 'Pago Mensual')], default='CONTADO', max_length=10, verbose_name='Modalidad de Pago')),
                ('plazo_meses', models.PositiveIntegerField(default=12, help_text='Relevante para pago a Crédito o Mensual', verbose_name='Plazo en Meses')),
                ('estado_cartera', models.CharField(choices=[('AL_DIA', 'Al día'), ('EN_MORA', 'En mora'), ('PAGO_COMPLETO', 'Pago Completo')], default='AL_DIA', max_length=15, verbose_name='Estado de Cartera')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=10, verbose_name='Estado de la Póliza')),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('monto_devolucion', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado al momento de la cancelación.', max_digits=12, null=True, verbose_name='Monto a Devolver')),
                ('comision_devuelta', models.DecimalField(blank=True, decimal_places=2, help_text='Comisión que Assecol retorna, calculada al cancelar.', max_digits=12, null=True, verbose_name='Comisión a Devolver')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to=settings.AUTH_USER_MODEL)),
                ('compania_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='polizas.companiaaseguradora')),
                ('tipo_seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='polizas.tiposeguro')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Opcional: Llenar solo si la póliza es para un vehículo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='polizas.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_fin'],
            },
        ),
    ]
