# Generated by Django 5.2.4 on 2025-07-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='comision_porcentaje',
        ),
        migrations.AddField(
            model_name='tiposeguro',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Porcentaje de Comisión (%)'),
        ),
    ]
