# Generated by Django 5.2.4 on 2025-09-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_poliza_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AlterField(
            model_name='poliza',
            name='asesor',
            field=models.ForeignKey(blank=True, help_text='El asesor que realizó la venta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polizas_vendidas', to='polizas.asesor'),
        ),
    ]
