# Generated by Django 5.2.4 on 2025-07-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_remove_poliza_comision_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='comision_devuelta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión que Assecol retorna, calculada al cancelar.', max_digits=12, null=True, verbose_name='Comisión a Devolver'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='monto_devolucion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado al momento de la cancelación.', max_digits=12, null=True, verbose_name='Monto a Devolver'),
        ),
    ]
