# Generated by Django 5.2.4 on 2025-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_poliza_comision_devuelta_poliza_monto_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='estado_cartera',
            field=models.CharField(choices=[('AL_DIA', 'Al día'), ('EN_MORA', 'En mora'), ('PAGO_COMPLETO', 'Pago Completo')], default='AL_DIA', max_length=15, verbose_name='Estado de Cartera'),
        ),
    ]
