# Generated by Django 5.2.4 on 2025-08-15 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_poliza_estado_cartera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa única del vehículo.', max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('soat_vencimiento_recordatorio', models.DateField(blank=True, help_text='Fecha de vencimiento del SOAT (incluso si no es de Assecol).', null=True, verbose_name='Recordatorio Vencimiento SOAT')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='poliza',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Opcional: Llenar solo si la póliza es para un vehículo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='polizas.vehiculo'),
        ),
    ]
