# Generated by Django 5.2.4 on 2025-09-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0005_vehiculo_poliza_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='prima_total',
        ),
        migrations.AddField(
            model_name='poliza',
            name='valor_prima_sin_iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=12, verbose_name='Valor Prima sin IVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiposeguro',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Ej: 19.00 para 19%', max_digits=5, verbose_name='Porcentaje de IVA (%)'),
        ),
    ]
