# Generated by Django 5.2.4 on 2025-07-22 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_MORA', 'En Mora')], default='PENDIENTE', max_length=10)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='polizas.poliza')),
            ],
            options={
                'ordering': ['numero_cuota'],
                'unique_together': {('poliza', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cartera.cuota')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
