# Generated by Django 5.2.4 on 2025-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado_comision',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Liquidar'), ('LIQUIDADA', 'Liquidada')], default='PENDIENTE', max_length=15, verbose_name='Estado de Liquidación'),
        ),
    ]
